export const ADD_TASK = "ADD_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const COMPLETE_TASK = "COMPLETE_TASK"
export const FETCH_TASK = "FETCH_TASK"
export const CHANGE_INPUT = "CHANGE_INPUT"
export const CLEAR_INPUT = "CLEAR_INPUT"
export const CHANGE_FILTER = "CHANGE_FILTER"